# Generated by Django 4.1.7 on 2023-03-22 09:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('apis', '0001_initial'),
        ('project', '0001_initial'),
        ('modules', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='apiinfo',
            name='module',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modules.module'),
        ),
        migrations.AddField(
            model_name='apiextract',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.project'),
        ),
    ]
