# Generated by Django 4.2.2 on 2023-06-09 01:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apiinfo',
            name='assert_text',
        ),
        migrations.RemoveField(
            model_name='apiinfo',
            name='assert_type',
        ),
        migrations.AlterField(
            model_name='apiextract',
            name='apis_id',
            field=models.IntegerField(default=0, verbose_name='接口ID'),
        ),
        migrations.CreateModel(
            name='ApiAssert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='名称')),
                ('assert_type', models.CharField(max_length=10, null=True, verbose_name='断言类型')),
                ('assert_extract', models.TextField(default='', null=True, verbose_name='断言提取表达式')),
                ('expect_text', models.TextField(default='', null=True, verbose_name='预期值')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('api', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apis.apiinfo')),
            ],
        ),
    ]
