# Generated by Django 4.2.2 on 2023-06-19 06:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0003_remove_apiinfo_assert_text_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='apiassert',
            options={'verbose_name': '断言信息保存表'},
        ),
        migrations.AlterModelOptions(
            name='apiextract',
            options={'verbose_name': '提取器保存表'},
        ),
        migrations.AlterModelOptions(
            name='apiinfo',
            options={'verbose_name': '项目信息表'},
        ),
        migrations.AlterModelTable(
            name='apiassert',
            table='t_api_assert',
        ),
        migrations.AlterModelTable(
            name='apiextract',
            table='t_api_extract',
        ),
        migrations.AlterModelTable(
            name='apiinfo',
            table='t_api_info',
        ),
    ]
