# Generated by Django 4.2.2 on 2023-06-19 06:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'verbose_name': '项目信息表'},
        ),
        migrations.AlterModelTable(
            name='project',
            table='t_project',
        ),
    ]
