# Generated by Django 4.2.2 on 2023-06-19 06:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='module',
            options={'verbose_name': '模块信息表'},
        ),
        migrations.AlterModelTable(
            name='module',
            table='t_module',
        ),
    ]
