# Generated by Django 4.1.7 on 2023-03-22 09:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Envs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='环境名称')),
                ('env', models.CharField(default='', max_length=50, null=True, verbose_name='环境值')),
                ('browser', models.CharField(default='', max_length=20, null=True, verbose_name='浏览器')),
                ('request_protocol', models.CharField(default='', max_length=200, null=True, verbose_name='URL')),
                ('base_url', models.CharField(default='', max_length=200, null=True, verbose_name='URL')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.project')),
            ],
        ),
    ]
