# Generated by Django 4.1.7 on 2023-05-23 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('envs', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='envs',
            old_name='project',
            new_name='project_id',
        ),
        migrations.RenameField(
            model_name='envs',
            old_name='request_protocol',
            new_name='protocol',
        ),
    ]
