# Generated by Django 4.1.7 on 2023-06-02 07:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HttpRunnerProjectInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='httpRunner项目名称')),
                ('describe', models.TextField(default='', null=True, verbose_name='描述')),
                ('code', models.TextField(default='', null=True, verbose_name='httpRunner debugTalk执行代码')),
                ('env_code', models.TextField(default='', null=True, verbose_name='httpRunner .env环境变量')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.project')),
            ],
        ),
    ]
