# Generated by Django 4.2.2 on 2023-06-09 01:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('httprunner_project', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HttpRunnerApiInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='api名称')),
                ('api_id', models.IntegerField(default=0, verbose_name='关联接口ID')),
                ('api_info', models.TextField(default='{}', null=True, verbose_name='接口信息')),
                ('summary', models.TextField(default='', null=True, verbose_name='测试结果信息')),
                ('result', models.TextField(default='', null=True, verbose_name='运行结果')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('httprunner_project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='httprunner_project.httprunnerprojectinfo')),
            ],
        ),
    ]
