# Generated by Django 4.2.2 on 2023-06-13 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('httprunner_project', '0004_httprunnerruninfo_remove_httprunnerapiinfo_result_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='httprunnerruninfo',
            name='httprunner_api_ids',
        ),
        migrations.AddField(
            model_name='httprunnerruninfo',
            name='ids',
            field=models.CharField(default=[], max_length=200, verbose_name='执行列表'),
        ),
        migrations.AddField(
            model_name='httprunnerruninfo',
            name='type',
            field=models.CharField(default='', max_length=50, verbose_name='类型(Api、TestCase、TestSuite)'),
        ),
    ]
