# Generated by Django 4.2.2 on 2023-06-19 06:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('httprunner_project', '0005_remove_httprunnerruninfo_httprunner_api_ids_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='httprunnerapiinfo',
            options={'verbose_name': 'HttpRunner接口信息表'},
        ),
        migrations.AlterModelOptions(
            name='httprunnerprojectinfo',
            options={'verbose_name': 'HttpRunner项目信息表'},
        ),
        migrations.AlterModelOptions(
            name='httprunnerruninfo',
            options={'verbose_name': 'HttpRunner执行结果信息表'},
        ),
        migrations.AlterModelTable(
            name='httprunnerapiinfo',
            table='t_httprunner_api_info',
        ),
        migrations.AlterModelTable(
            name='httprunnerprojectinfo',
            table='t_httprunner_project',
        ),
        migrations.AlterModelTable(
            name='httprunnerruninfo',
            table='t_httprunner_run_info',
        ),
    ]
