# Generated by Django 4.2.2 on 2023-06-29 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('httprunner_project', '0007_httprunnerapiprocessor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='httprunnerapiprocessor',
            name='post_processor',
        ),
        migrations.RemoveField(
            model_name='httprunnerapiprocessor',
            name='pre_processor',
        ),
        migrations.AddField(
            model_name='httprunnerapiprocessor',
            name='processor_code',
            field=models.TextField(default='', null=True, verbose_name='代码'),
        ),
    ]
