# Generated by Django 4.2.2 on 2023-06-29 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('httprunner_project', '0008_remove_httprunnerapiprocessor_post_processor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='httprunnerapiprocessor',
            name='processor_type',
            field=models.CharField(default='', max_length=50, verbose_name='处理器代码类型（PRE-前置，POST-后置）'),
        ),
    ]
