# Generated by Django 4.2.2 on 2023-07-11 01:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('httprunner_project', '0010_rename_httprunnerapiprocessor_httprunnerprocessor_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='httprunnertestcaseinfo',
            name='httpruuner_api_ids',
        ),
    ]
