# Generated by Django 4.2.2 on 2023-07-11 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('httprunner_project', '0011_remove_httprunnertestcaseinfo_httpruuner_api_ids'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='httprunnerprocessor',
            name='httprunner_api_id',
        ),
        migrations.RemoveField(
            model_name='httprunnerprocessor',
            name='httprunner_case_id',
        ),
        migrations.RemoveField(
            model_name='httprunnerprocessor',
            name='httprunner_suite_id',
        ),
        migrations.AddField(
            model_name='httprunnerprocessor',
            name='httprunner_id',
            field=models.IntegerField(default=0, null=True, verbose_name='关联接口/用例/用例集ID'),
        ),
    ]
