# Generated by Django 4.1.7 on 2023-05-31 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Infos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='文件名称')),
                ('url', models.CharField(max_length=255, verbose_name='接口地址')),
                ('method', models.CharField(max_length=10, verbose_name='请求方法')),
                ('request_headers', models.TextField(default='[]', null=True, verbose_name='请求头信息')),
                ('request_params', models.TextField(default='[]', null=True, verbose_name='请求参数param')),
                ('request_body', models.TextField(default='{}', null=True, verbose_name='参数内容')),
                ('response_body', models.TextField(default='{}', null=True, verbose_name='响应')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
        ),
    ]
