# Generated by Django 4.2.2 on 2023-06-19 06:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_infos', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='infos',
            options={'verbose_name': '解析接口信息表'},
        ),
        migrations.AlterModelTable(
            name='infos',
            table='t_tripartite_api_info',
        ),
    ]
