# Generated by Django 4.2.2 on 2023-12-11 02:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("project", "0002_alter_project_options_alter_project_table"),
        ("modules", "0002_alter_module_options_alter_module_table"),
    ]

    operations = [
        migrations.CreateModel(
            name="CasesSuite",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, verbose_name="名称")),
                (
                    "describe",
                    models.TextField(default="", null=True, verbose_name="描述"),
                ),
                ("parent_id", models.IntegerField(default=0, verbose_name="测试用例集父级ID")),
                (
                    "case_ids",
                    models.CharField(
                        default=0, max_length=200, null=True, verbose_name="关联用例id"
                    ),
                ),
                (
                    "status",
                    models.BooleanField(default=False, verbose_name="状态 0-未执行 1-已执行"),
                ),
                (
                    "create_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "update_time",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
            ],
            options={
                "verbose_name": "测试用例集",
                "db_table": "t_cases_suite",
            },
        ),
        migrations.CreateModel(
            name="TestStep",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, verbose_name="测试用例名称")),
                ("test_step", models.CharField(max_length=255, verbose_name="测试步骤")),
                ("test_data", models.CharField(max_length=255, verbose_name="测试数据")),
                (
                    "expected_result",
                    models.CharField(max_length=255, verbose_name="预期结果"),
                ),
                (
                    "actual_result",
                    models.CharField(
                        default="", max_length=255, null=True, verbose_name="实际结果"
                    ),
                ),
                (
                    "step_status",
                    models.IntegerField(
                        default=0, null=True, verbose_name="测试步骤执行测试结果：1-未通过 2-通过"
                    ),
                ),
                (
                    "api_id",
                    models.IntegerField(default=0, null=True, verbose_name="接口id"),
                ),
                (
                    "describe",
                    models.TextField(default="", null=True, verbose_name="描述"),
                ),
                (
                    "create_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "update_time",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
            ],
            options={
                "verbose_name": "测试步骤集",
                "db_table": "t_test_step",
            },
        ),
        migrations.CreateModel(
            name="VersionInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, verbose_name="需求名称")),
                ("version_number", models.CharField(max_length=50, verbose_name="版本号")),
                (
                    "requirements_type",
                    models.CharField(
                        max_length=20, verbose_name="需求类型：业务类需求/Bug改进需求/技术类需求"
                    ),
                ),
                (
                    "requirements",
                    models.TextField(
                        default="", null=True, verbose_name="该版本的需求文本/链接/文件/图片"
                    ),
                ),
                (
                    "requirements_upload_file",
                    models.TextField(
                        default="", null=True, verbose_name="需求上传的文件/图片-列表"
                    ),
                ),
                (
                    "demand_analysis",
                    models.TextField(
                        default="", null=True, verbose_name="需求分析/链接/文本/图片/视频"
                    ),
                ),
                (
                    "describe",
                    models.TextField(default="", null=True, verbose_name="版本说明"),
                ),
                (
                    "is_delete",
                    models.BooleanField(default=False, null=True, verbose_name="是否删除"),
                ),
                (
                    "create_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "update_time",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="project.project",
                    ),
                ),
            ],
            options={
                "verbose_name": "版本信息表",
                "db_table": "t_test_version_info",
            },
        ),
        migrations.CreateModel(
            name="TestCase",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "version_number",
                    models.CharField(max_length=200, verbose_name="版本id集合"),
                ),
                ("name", models.CharField(max_length=50, verbose_name="测试用例名称")),
                ("type", models.IntegerField(verbose_name="测试类型：1-功能测试，2-接口测试")),
                (
                    "test_label",
                    models.IntegerField(verbose_name="测试标签：1-正向场景测试用例，2-异常场景测试用例"),
                ),
                (
                    "importance",
                    models.IntegerField(verbose_name="重要程度：1-P0，2-P1，3-P2，4-P3"),
                ),
                (
                    "priority",
                    models.IntegerField(
                        default=0, null=True, verbose_name="优先级：1-高，2-中，3-低"
                    ),
                ),
                (
                    "precondition",
                    models.TextField(default="", null=True, verbose_name="前置条件"),
                ),
                (
                    "test_steps",
                    models.CharField(max_length=200, verbose_name="关联测试步骤集"),
                ),
                (
                    "status",
                    models.IntegerField(
                        default=0, null=True, verbose_name="用例状态：1-未执行，2-执行中，3-已执行"
                    ),
                ),
                (
                    "result_status",
                    models.IntegerField(
                        default=0, null=True, verbose_name="执行结果：1-失败，2-通过"
                    ),
                ),
                (
                    "bug_list",
                    models.CharField(
                        default="", max_length=200, null=True, verbose_name="Bug列表"
                    ),
                ),
                ("remark", models.TextField(default="", null=True, verbose_name="备注")),
                (
                    "create_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "update_time",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "module",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="modules.module"
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="project.project",
                    ),
                ),
            ],
            options={
                "verbose_name": "测试用例表",
                "db_table": "t_test_case",
            },
        ),
    ]
