# Generated by Django 4.2.2 on 2023-12-11 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cases", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="teststep",
            name="describe",
        ),
        migrations.AddField(
            model_name="teststep",
            name="remark",
            field=models.TextField(default="", null=True, verbose_name="备注"),
        ),
    ]
