# Generated by Django 4.2.2 on 2023-12-12 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cases", "0002_remove_teststep_describe_teststep_remark"),
    ]

    operations = [
        migrations.AddField(
            model_name="testcase",
            name="is_delete",
            field=models.BooleanField(default=False, null=True, verbose_name="是否删除"),
        ),
    ]
