# Generated by Django 4.2.2 on 2023-12-13 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cases", "0003_testcase_is_delete"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="casessuite",
            name="parent_id",
        ),
        migrations.AddField(
            model_name="casessuite",
            name="version_number",
            field=models.CharField(
                default="", max_length=200, verbose_name="版本version_number"
            ),
        ),
        migrations.AlterField(
            model_name="casessuite",
            name="status",
            field=models.BooleanField(
                default=False, verbose_name="状态 0-未执行 1-执行中 2-已执行"
            ),
        ),
    ]
