# Generated by Django 4.2.2 on 2023-12-13 04:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cases", "0004_remove_casessuite_parent_id_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="testcase",
            name="status",
        ),
    ]
