# Generated by Django 4.2.2 on 2023-12-13 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cases", "0006_casessuite_is_delete"),
    ]

    operations = [
        migrations.AlterField(
            model_name="casessuite",
            name="status",
            field=models.BooleanField(
                default=0, null=True, verbose_name="状态 0-未执行 1-执行中 2-已执行"
            ),
        ),
    ]
