# Generated by Django 4.2.2 on 2023-12-14 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cases", "0007_alter_casessuite_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="casessuite",
            name="status",
            field=models.CharField(
                default=0, max_length=10, null=True, verbose_name="状态 0-未执行 1-执行中 2-已执行"
            ),
        ),
    ]
